### ISSUE TITLE
The npm link is broken and I can't find it using npm install @chillerlan/qrcode

### ISSUE THREAD

**Issue by mattwright** [chillerlan/js-qrcode#5]
The npm link in README.md points to https://github.com/chillerlan/js-qrcode/pkgs/npm/qrcode which is broken.

**Comment by codemasher** [comment]
The link is not broken, it's just a bit complicated to install packages from GitHub it seems (i didn't realize this when i published).

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry#installing-a-package

I might as well move the package to NPM at some point.

**Comment by codemasher** [comment]
Please try this and let me know if it works for you: https://www.npmjs.com/package/@chillerlan/qrcode

**Comment by mattwright** [comment]
Excellent -- thank you! Sorry, I didn't understand originally that I needed to use a different registry.

**Comment by codemasher** [comment]
Yea the different registry thing is a bit weird, but also when i deleted the package here on GH, i noticed it was set to private for whatever reason, which is probably why it appeared broken for you.

**Comment by mattwright** [comment]
Yeah, definitely had gotten a 404 error on that link yesterday, so must have been the private setting if I was supposed to be able to see something there. Thanks for fixing it so quick!
